clear all;
constants;
pePto;

result_limit = [1 10 100];

cost_send = 64 + 51;
cost_unsuccessful = 64 + 4;
cost_successful = 64 + 4 + 6.*result_limit;

hits_per_query = z*awareness(round(mean_peers))/n;
miss_per_query = z - hits_per_query;

queries_hour = n*q.*z ./(1-(1-awareness(round(mean_peers),:)./n).^z);

results_one = queries_hour.*(cost_send + ...
              cost_unsuccessful*miss_per_query + ...
              cost_successful(1)*hits_per_query); % B/h
results_ten = queries_hour.*(cost_send + ...
              cost_unsuccessful*miss_per_query + ...
              cost_successful(2)*hits_per_query);
results_hun = queries_hour.*(cost_send + ...
              cost_unsuccessful*miss_per_query + ...
              cost_successful(3)*hits_per_query);

colheadings = {'z','r(1)','#queries/hour','a=1', '+%','a=10', '+%','a=100', '+%'}; 
rowheadings = {};
data = [z'...
        r_1'...
        round(queries_hour')...
        round((results_one/(10^9*60*60))')...
        (round(100*100*results_one/(4656*10^15/(52/12*7*24)))/100)'...
        round((results_ten/(10^9*60*60))')...
        (round(100*100*results_ten/(4656*10^15/(52/12*7*24)))/100)'...
        round((results_hun/(10^9*60*60))')...
        (round(100*100*results_hun/(4656*10^15/(52/12*7*24)))/100)'];

colsep = ' & '; 
rowending = ' \\';
wid = 11; 
fms = {'d','d','d','d','d','d','d','d','d'};
fileID = 1;

displaytable(data,colheadings,wid,fms,rowheadings,fileID,colsep,rowending);